# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maze < Formula
  desc ""
  homepage "https://github.com/MAZE-MultiCloud/maze-cli"
  version "1.0"

  on_macos do
    url "https://github.com//MAZE-MultiCloud/maze-cli/releases/download/1.0/maze_Darwin_all.tar.gz"
    sha256 "bff569a8e38b5a39ec5b5745e3404acec103f248c3b628df0a3910d90273e47d"

    def install
      bin.install "maze"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com//MAZE-MultiCloud/maze-cli/releases/download/1.0/maze_Linux_x86_64.tar.gz"
        sha256 "5817ef61567c40417a305fca4a7bd57774277fbb26b01260aa524d0a1a41f44d"

        def install
          bin.install "maze"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com//MAZE-MultiCloud/maze-cli/releases/download/1.0/maze_Linux_arm64.tar.gz"
        sha256 "9828e27e05275cd327c5a1f0a3cd622eaad265cfed994a0b39c27c61aee0a341"

        def install
          bin.install "maze"
        end
      end
    end
  end
end
