# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maze < Formula
  desc ""
  homepage "https://github.com/MAZE-MultiCloud/maze-cli"
  version "1.0"

  on_macos do
    url "https://github.com//MAZE-MultiCloud/maze-cli/releases/download/1.0/maze-cli_Darwin_all.tar.gz"
    sha256 "1ef884b9b97c7b5abfa1f437b7ac5bc8f77d2a1ce8abb99a43cbcb670b4201e8"

    def install
      bin.install "maze-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com//MAZE-MultiCloud/maze-cli/releases/download/1.0/maze-cli_Linux_x86_64.tar.gz"
        sha256 "b7254527d4a3a0f195fafeb792ba056cf1b6995eb27ecb7add0a7ca0a10316ad"

        def install
          bin.install "maze-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com//MAZE-MultiCloud/maze-cli/releases/download/1.0/maze-cli_Linux_arm64.tar.gz"
        sha256 "6e79d3870215e1be37522381cf976b55523a048d844c19b9c85dd3808adba4f1"

        def install
          bin.install "maze-cli"
        end
      end
    end
  end
end
