# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maze < Formula
  desc ""
  homepage "https://github.com/MAZE-MultiCloud/maze-cli"
  version "1.0"

  on_macos do
    url "https://github.com/MAZE-Multicloud/maze-cli/releases/download/1.0/maze_Darwin_all.tar.gz"
    sha256 "01659654bd353bdabfdec0de8faa20227ef161cd00f9f1143a7363bbb10e9801"

    def install
      bin.install "maze"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MAZE-Multicloud/maze-cli/releases/download/1.0/maze_Linux_x86_64.tar.gz"
        sha256 "8f9ed6be87568417076fa7bfe4d19d60cccfad324317a4b1c096cc8311d5d787"

        def install
          bin.install "maze"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MAZE-Multicloud/maze-cli/releases/download/1.0/maze_Linux_arm64.tar.gz"
        sha256 "97a13657940c905d89324e79758fd6fa4a1c4eeaa2528ac849ab5271a05995d0"

        def install
          bin.install "maze"
        end
      end
    end
  end
end
